### PR TITLE
⚛️  Upgrade to React 18

### LINKED ISSUE #28: [Update] React 18.0.0
As the title says, please update for react 18.0.0

image

### PR DESCRIPTION
**Pull request by marcofugaro**
Fixes #28

### CODE REVIEW

**Comment by marcofugaro** [comment]
Still some issues with rendering (OrbitControls)

**Comment by mcgingras** [comment]
would love for this to get merged

**Comment by marcofugaro** [comment]
All fixed.

**Comment by marcofugaro** [comment]
Version `v2.1.0` has been released!

**Pull request merged**
